- hosts: workstation
  user: fmarinho
  become: yes
  gather_facts: false
  tasks:
  - name: Installing baseline file
    template:
      src:   files/baseline.template
      dest:  /etc/sysctl.d/90-security-baseline.conf
      owner: root
      group: root
      mode:  0660
  - name: Make the kernel read the security-baseline file
    command: sysctl --system
