- hosts: servers
  user: fmarinho
  become: yes
  connection: ssh
  gather_facts: false
  tasks:
   - name: INSTALLING POSTGRESQL PACKAGE AND DEPENDENCIES
     yum:
       name:  postgresql-server
       state: latest
