- hosts: workstation
  user: fmarinho
  become: yes
  gather_facts: false
  tasks:
  - name: Installing baseline file
    template:
      src:  /home/fmarinho/linux-academy/devops/ansible/baseline.template
      dest: /etc/sysctl.d/90-security-baseline.conf
      owner: root
      group: root
      mode: "u=rw,g=r,o=r"
  - name: Make the kernel read the security-baseline file
    command: sysctl --system
