- hosts: all
  user: fmarinho
  become: yes
  gather_facts: false
  tasks:
   - name: INSTALLING THE 'DEVELOPMENT TOOLS' PACKAGE GROUP
     yum:
       name: "@Development Tools"
       state: present
