- hosts: servers
  user: fmarinho
  become: yes
  connection: ssh
  gather_facts: false
  tasks:
   - name: INSTALLING YUM-UTILS PACKAGE
     yum:
       name:  yum-utils
       state: present
   - name: REMOVING OLD KERNELS FROM THE SYSTEM
     command: package-cleanup --oldkernels -y
