- hosts: all
  user: fmarinho
  become: yes
  gather_facts: false
  tasks:
  - name: ADD GROUP MCUNHA
    group:
      name: mcunha
      gid: 1003
      state: present   
  - name: ADD USER MCUNHA
    user:
      name: mcunha
      comment: Marcial Cunha
      uid: 1003
      shell: /bin/bash
      group: mcunha
      groups: wheel
      state: present
      generate_ssh_key: yes
      ssh_key_bits: 2048
      ssh_key_file: .ssh/id_rsa
