- hosts: servers
  user: fmarinho
  become: yes
  connection: ssh
  gather_facts: false
  tasks:
   - name: ENSURE THE NGINX SERVICE IS NOT RUNNING
     service:
       name:  nginx
       state: stopped
