- hosts: servers
  user: fmarinho
  become: yes
  connection: ssh
  gather_facts: false
  tasks:
  - name: HARDENING FSTAB FILE
    file: 
      path: /etc/fstab
      owner: root
      group: root
      mode:  0660
      attributes: i
