- hosts: all
  user: fmarinho
  become: yes
  gather_facts: false
  tasks:
  - name: HARDENING FSTAB FILE
    file: 
      path: /etc/fstab
      owner: root
      group: root
      mode: 0660
      attributes: i
