- hosts: all
  user: fmarinho
  become: yes
  gather_facts: false
  tasks:
   - name: INSTALLING NGINX
     yum:
       name: nginx
       state: present
   - name: INSTALLING THE DEVELOPMENT GROUP PACKAGES
     yum:
       name: "@Development tools"
       state: present
   - name: INSTALLING THE OPENSSL-DEVEL PACKAGES
     yum:
       name:  openssl-devel
       state: present
   - name: INSTALLING YUM-UTIL PACKAGES
     yum:
       name: yum-utils
       state: present
   - name: INSTALLING VIM PACKAGE AND DEPENDENCIES
     yum:
       name: vim
       state: present
